cloud:
  aws:
    credentials:
      access-key: AKIAXQXUCFPGVNQFOX3A
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: springs3testing


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090